# Site settings
title: Book about Music
email: kaceong@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Do you like to read about Music?
  This is an awesome book that I wrote.
baseurl: "/bookmusic" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: ssqwwq
github_username:  iiudiu

# Build settings
markdown: kramdown
